version: "3.0"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  promgateway:
    image: prom/pushgateway
    container_name: promgateway
    restart: always
    ports:
      - "9091:9091"
    volumes:
      - /etc/localtime:/etc/localtime:ro
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "23000:3000"
    environment:
      - "GF_SECURITY_ADMIN_PASSWORD=abcd.1234"
    restart: "always"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./grafana:/var/lib/grafana
  
  loki:
    image: grafana/loki:2.5.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.5.0
    container_name: promtail
    volumes:
      - ./promtail/log:/var/log
      - ./promtail/config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml